version: '3.1'

services:

  wordpress:
    image: wordpress
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: root
      WORDPRESS_DB_NAME: cambosino
    volumes:
      - ./:/var/www/html
    ports:
      - 80:80

  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: cambosino
      MYSQL_USER: cambosino
      MYSQL_PASSWORD: cambosino
      MYSQL_ROOT_PASSWORD: root
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    ports:
      - 3306:3306

  adminer:
    image: adminer
    ports:
      - 8080:8080

volumes:
  wordpress:
  db:
