name: Deployment

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: production
    concurrency: production

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup ssh key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh -o "StrictHostKeyChecking=no" admin@108.61.250.9 "echo 123"

#      - name: Deploy to server
#        run: |
#          scp -o "StrictHostKeyChecking=no" .github/deploy.sh admin@108.61.250.9:/tmp/
#          ssh -o "StrictHostKeyChecking=no" admin@108.61.250.9 "bash /tmp/deploy.sh"

#      - name: Install node dependencies
#        run: |
#          ssh -o "StrictHostKeyChecking=no" admin@108.61.250.9 "cd /home/admin/web/cambosino.com/public_html/wp-content/themes/cambosino && yarn install --frozen-lockfile && yarn run compile:css"
